[package]
name = "bevy_undo"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "despawn"
path = "examples/despawn.rs"


[[example]]
name = "despawn_2entities"
path = "examples/despawn_2entities.rs"


[[example]]
name = "despawn_2entities_on_1frame"
path = "examples/despawn_2entities_on_1frame.rs"


[dependencies]
bevy = "0.11.0"
itertools = "0.11.0"
bevy_tweening = { version = "0.8.0", optional = true }

[dev-dependencies]
bevy_tweening = "0.8.0"
bevy_undo = { path = "./", features = ["tween"] }


[features]
default = []
tween = ["bevy_tweening"]